name: Publish PostgreSQL Package

on:
  release:
    types: [published]

env:
  PACKAGE_NAME: 'pg'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'pg-v') || startsWith(github.event.release.tag_name, '@iamkirbki/database-handler-pg@')
    defaults:
        run:
            working-directory: ./packages/pg
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org/"
      
      - name: Install pg dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build pg package
        run: npm run build
      
      - name: Publish pg package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
