name: Publish NPM Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org/"
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build all packages
        run: npm run build --workspaces --if-present
      
      - name: Publish core package
        run: npm publish --access public
        working-directory: ./packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish better-sqlite3 package
        run: npm publish --access public
        working-directory: ./packages/better-sqlite3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish pg package
        run: npm publish --access public
        working-directory: ./packages/pg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}